import { useMemo, useState } from "react";

const products=[
{id:1,title:"Engineering Mathematics — 2nd Sem",price:280,oldPrice:450,category:"Books",condition:"Like New",seller:"Aarav",initials:"AS",location:"Hostel Block A",image:"https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=900&q=80"},
{id:2,title:"Scientific Calculator FX-991ES",price:650,oldPrice:1100,category:"Electronics",condition:"Excellent",seller:"Riya",initials:"RK",location:"Block C",image:"https://images.unsplash.com/photo-1587145820266-a5951ee6f620?auto=format&fit=crop&w=900&q=80"},
{id:3,title:"Study Table — Compact",price:1200,oldPrice:2200,category:"Furniture",condition:"Good",seller:"Dev",initials:"DP",location:"Boys Hostel",image:"https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=900&q=80"},
{id:4,title:"College Backpack",price:500,oldPrice:999,category:"Accessories",condition:"Like New",seller:"Mehak",initials:"MS",location:"Library",image:"https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80"},
{id:5,title:"Arduino Uno Starter Kit",price:900,oldPrice:1450,category:"Electronics",condition:"Excellent",seller:"Kunal",initials:"KS",location:"Lab Complex",image:"https://images.unsplash.com/photo-1553406830-ef2513450d76?auto=format&fit=crop&w=900&q=80"},
{id:6,title:"Desk Lamp",price:350,oldPrice:650,category:"Hostel Essentials",condition:"Good",seller:"Ananya",initials:"AJ",location:"Girls Hostel",image:"https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=80"},
{id:7,title:"DBMS & OS Notes Bundle",price:180,oldPrice:300,category:"Books",condition:"Good",seller:"Yash",initials:"YM",location:"Academic Block",image:"https://images.unsplash.com/photo-1456324504439-367cee3b3c32?auto=format&fit=crop&w=900&q=80"},
{id:8,title:"Gaming Mouse",price:750,oldPrice:1299,category:"Electronics",condition:"Like New",seller:"Ishaan",initials:"IP",location:"Block B",image:"https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=900&q=80"}];

const categories=[["Books","▤","842 items"],["Electronics","⌁","326 items"],["Furniture","▥","184 items"],["Hostel Essentials","⌂","276 items"],["Accessories","◈","215 items"],["Clothing","◇","139 items"]];

export default function App(){
const [activeCategory,setActiveCategory]=useState("All"),[search,setSearch]=useState(""),[selected,setSelected]=useState(null),[showSell,setShowSell]=useState(false),[showLogin,setShowLogin]=useState(false),[favorites,setFavorites]=useState([]),[toast,setToast]=useState("");
const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return products.filter(p=>(activeCategory==="All"||p.category===activeCategory)&&(!q||[p.title,p.category,p.seller,p.location].some(v=>v.toLowerCase().includes(q))))},[activeCategory,search]);
const notify=m=>{setToast(m);clearTimeout(window.__ckt);window.__ckt=setTimeout(()=>setToast(""),2400)};
const chooseCategory=c=>{setActiveCategory(c);document.getElementById("marketplace")?.scrollIntoView({behavior:"smooth"})};
return <div className="app-shell">
<header className="navbar"><div className="nav-inner">
<button className="brand" onClick={()=>{setActiveCategory("All");setSearch("");window.scrollTo({top:0,behavior:"smooth"})}}><span className="brand-mark">K</span><span>Campus<span>Kart</span></span></button>
<nav className="nav-links"><button className="active">Marketplace</button><button onClick={()=>document.getElementById("how-it-works")?.scrollIntoView({behavior:"smooth"})}>How it works</button><button onClick={()=>notify("Community features are coming next.")}>Community</button></nav>
<div className="nav-actions"><button className="icon-btn" onClick={()=>notify("You're all caught up.")}>♢<span className="notification-dot"/></button><button className="sell-btn" onClick={()=>setShowSell(true)}>＋ Sell an item</button><button className="profile-btn" onClick={()=>setShowLogin(true)}><span className="avatar small">S</span><span className="profile-name">Sambhav</span><span className="chevron">⌄</span></button></div>
</div></header>
<main>
<section className="hero"><div className="hero-glow one"/><div className="hero-glow two"/><div className="hero-inner">
<div className="hero-copy"><div className="eyebrow"><span className="pulse"/> GNIOT student marketplace</div><h1>Buy smarter.<br/><em>Sell easier.</em><br/>Stay on campus.</h1><p>Everything students need, exchanged within their own campus community.</p>
<div className="hero-search"><span className="search-icon">⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search books, electronics, furniture..."/><button onClick={()=>document.getElementById("marketplace")?.scrollIntoView({behavior:"smooth"})}>Search</button></div>
<div className="hero-meta"><span><b>2.4k+</b> listings</span><i/><span><b>1.8k+</b> students</span><i/><span><b>98%</b> campus verified</span></div></div>
<div className="hero-art"><div className="float-card card-a"><span className="float-icon green">✓</span><div><strong>Sold!</strong><small>Engineering book</small></div><b>₹280</b></div><div className="product-visual"><div className="visual-grid"/><div className="phone"><div className="phone-notch"/><div className="phone-screen"><div className="mini-brand"><span>K</span> CampusKart</div><div className="mini-search">⌕ Search anything...</div><div className="mini-cats"><span>Books</span><span>Tech</span><span>Hostel</span></div><div className="mini-card"><img src={products[0].image}/><div><b>Maths — 2nd Sem</b><small>Like New</small><strong>₹280</strong></div></div><div className="mini-card second"><img src={products[3].image}/><div><b>College Backpack</b><small>Like New</small><strong>₹500</strong></div></div></div></div></div><div className="float-card card-b"><span className="float-icon blue">♢</span><div><strong>Campus verified</strong><small>Safe student-to-student</small></div></div></div>
</div></section>
<section className="category-section"><div className="section-head compact"><div><span className="section-kicker">Explore</span><h2>Shop by category</h2></div><button className="text-btn" onClick={()=>{setActiveCategory("All");setSearch("")}}>View all <span>→</span></button></div>
<div className="category-grid">{categories.map(([name,icon,count])=><button className={activeCategory===name?"category-card selected":"category-card"} key={name} onClick={()=>chooseCategory(name)}><span className={"category-icon "+name.toLowerCase().replaceAll(" ","-")}>{icon}</span><div><strong>{name}</strong><small>{count}</small></div><span className="category-arrow">↗</span></button>)}</div></section>
<section className="marketplace-section" id="marketplace"><div className="section-head"><div><span className="section-kicker">Fresh on campus</span><h2>Popular listings</h2><p>{filtered.length} items matching your search</p></div><div className="sort-row"><button className="filter-btn" onClick={()=>notify("Filters will be connected to the backend next.")}>☷ Filters</button><select onChange={()=>notify("Sorting preference saved for this session.")}><option>Recommended</option><option>Newest first</option><option>Price: low to high</option></select></div></div>
<div className="product-grid">{filtered.map(p=><article className="product-card" key={p.id}><button className="heart" onClick={()=>setFavorites(f=>f.includes(p.id)?f.filter(x=>x!==p.id):[...f,p.id])}>{favorites.includes(p.id)?"♥":"♡"}</button><button className="product-image" onClick={()=>setSelected(p)}><img src={p.image} alt={p.title}/><span className="condition">{p.condition}</span></button><div className="product-info"><div className="product-category">{p.category}</div><button className="product-title" onClick={()=>setSelected(p)}>{p.title}</button><div className="price-row"><strong>₹{p.price.toLocaleString("en-IN")}</strong><del>₹{p.oldPrice.toLocaleString("en-IN")}</del><span>{Math.round((1-p.price/p.oldPrice)*100)}% off</span></div><div className="seller-row"><span className="avatar">{p.initials}</span><span><b>{p.seller}</b><small> · {p.location}</small></span><button onClick={()=>setSelected(p)}>View →</button></div></div></article>)}</div>
{!filtered.length&&<div className="empty-state"><span>⌕</span><h3>No listings found</h3><p>Try a different search or category.</p><button onClick={()=>{setSearch("");setActiveCategory("All")}}>Clear search</button></div>}</section>
<section className="trust-section" id="how-it-works"><div className="trust-copy"><span className="section-kicker">Built for campus life</span><h2>A marketplace that feels like your campus.</h2><p>No strangers. No complicated shipping. Just students helping students get more value from things they already own.</p><button className="primary-btn" onClick={()=>setShowSell(true)}>List your first item <span>→</span></button></div><div className="steps"><div className="step"><span>01</span><div><h3>Post in seconds</h3><p>Add a photo, price and a few details. That's it.</p></div></div><div className="step"><span>02</span><div><h3>Connect locally</h3><p>Chat with verified students from your campus.</p></div></div><div className="step"><span>03</span><div><h3>Meet & exchange</h3><p>Agree on a spot and complete the handoff on campus.</p></div></div></div></section>
</main>
<footer><div className="footer-brand"><span className="brand-mark">K</span><div><b>CampusKart</b><small>Your campus. Your marketplace.</small></div></div><div className="footer-note">Made for students, by students <span>✦</span></div><div className="footer-links"><button>Privacy</button><button>Help</button><button onClick={()=>notify("Thanks for the feedback!")}>Feedback</button></div></footer>
{selected&&<div className="modal-backdrop" onMouseDown={()=>setSelected(null)}><div className="product-modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSelected(null)}>×</button><img src={selected.image} alt={selected.title}/><div className="modal-content"><span className="product-category">{selected.category}</span><h2>{selected.title}</h2><div className="modal-price">₹{selected.price.toLocaleString("en-IN")} <del>₹{selected.oldPrice.toLocaleString("en-IN")}</del></div><p>This item is listed by a verified campus student. Connect with the seller to ask questions and arrange a convenient campus handoff.</p><div className="seller-detail"><span className="avatar">{selected.initials}</span><div><b>{selected.seller}</b><small>Verified student · {selected.location}</small></div><span className="verified">✓ Verified</span></div><button className="primary-btn full" onClick={()=>{setSelected(null);notify("Chat opened — seller contact is ready for the demo.")}}>Message seller <span>→</span></button></div></div></div>}
{showSell&&<Modal title="List an item" onClose={()=>setShowSell(false)}><p className="modal-intro">Create a quick demo listing. Backend submission will be connected next.</p><div className="form-grid"><label>Item name<input placeholder="e.g. Engineering Mathematics book"/></label><label>Category<select><option>Books</option><option>Electronics</option><option>Furniture</option><option>Hostel Essentials</option><option>Accessories</option></select></label><label>Price (₹)<input type="number" placeholder="500"/></label><label>Condition<select><option>Like New</option><option>Excellent</option><option>Good</option></select></label><label className="full-field">Description<textarea placeholder="Tell buyers a little about the item..."/></label></div><button className="primary-btn full" onClick={()=>{setShowSell(false);notify("Demo listing saved! Backend connection comes next.")}}>Publish listing <span>→</span></button></Modal>}
{showLogin&&<Modal title="Welcome back" onClose={()=>setShowLogin(false)}><p className="modal-intro">Sign in with your college account to continue.</p><label className="form-label">College email<input type="email" placeholder="you@gniot.net.in"/></label><label className="form-label">Password<input type="password" placeholder="••••••••"/></label><button className="primary-btn full" onClick={()=>{setShowLogin(false);notify("Demo sign-in successful.")}}>Continue <span>→</span></button><div className="or"><span>or</span></div><button className="google-btn" onClick={()=>notify("Google sign-in will be connected later.")}>Continue with Google</button></Modal>}
{toast&&<div className="toast"><span>✓</span>{toast}</div>}
</div>
}

function Modal({title,onClose,children}){return <div className="modal-backdrop" onMouseDown={onClose}><div className="form-modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={onClose}>×</button><span className="section-kicker">CampusKart</span><h2>{title}</h2>{children}</div></div>}